17:09:01.696 [main] ERROR o.s.b.SpringApplication - [reportFailure,824] - Application run failed
java.lang.IllegalStateException: Unable to read meta-data for class com.hy.sys.common.config.RedisConfigcom.hy.sys.common.config.RedissonConfig
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:237)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getOrder(AutoConfigurationSorter.java:208)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.access$000(AutoConfigurationSorter.java:154)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter.lambda$getInPriorityOrder$0(AutoConfigurationSorter.java:63)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$$Lambda$344/680150616.compare(Unknown Source)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.util.TimSort.sort(TimSort.java:230)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter.getInPriorityOrder(AutoConfigurationSorter.java:62)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.sortAutoConfigurations(AutoConfigurationImportSelector.java:474)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.selectImports(AutoConfigurationImportSelector.java:459)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:882)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.hy.sys.auth.HyAuthApplication.main(HyAuthApplication.java:14)
Caused by: java.io.FileNotFoundException: class path resource [com/hy/sys/common/config/RedisConfigcom/hy/sys/common/config/RedissonConfig.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199)
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:233)
	... 28 common frames omitted
17:10:09.901 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper.<clinit>(AddressResolverGroupProvider.java:58)

The following method did not exist:

    io.netty.resolver.dns.DnsNameResolverBuilder.socketChannelType(Ljava/lang/Class;)Lio/netty/resolver/dns/DnsNameResolverBuilder;

The calling method's class, io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper, was loaded from the following location:

    jar:file:/C:/Users/Administrator/.m2/repository/io/lettuce/lettuce-core/6.1.8.RELEASE/lettuce-core-6.1.8.RELEASE.jar!/io/lettuce/core/resource/AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper.class

The called method's class, io.netty.resolver.dns.DnsNameResolverBuilder, is available from the following locations:

    jar:file:/C:/Users/Administrator/.m2/repository/io/netty/netty-resolver-dns/4.1.35.Final/netty-resolver-dns-4.1.35.Final.jar!/io/netty/resolver/dns/DnsNameResolverBuilder.class

The called method's class hierarchy was loaded from the following locations:

    io.netty.resolver.dns.DnsNameResolverBuilder: file:/C:/Users/Administrator/.m2/repository/io/netty/netty-resolver-dns/4.1.35.Final/netty-resolver-dns-4.1.35.Final.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper and io.netty.resolver.dns.DnsNameResolverBuilder

17:10:42.795 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper.<clinit>(AddressResolverGroupProvider.java:58)

The following method did not exist:

    io.netty.resolver.dns.DnsNameResolverBuilder.socketChannelType(Ljava/lang/Class;)Lio/netty/resolver/dns/DnsNameResolverBuilder;

The calling method's class, io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper, was loaded from the following location:

    jar:file:/C:/Users/Administrator/.m2/repository/io/lettuce/lettuce-core/6.1.8.RELEASE/lettuce-core-6.1.8.RELEASE.jar!/io/lettuce/core/resource/AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper.class

The called method's class, io.netty.resolver.dns.DnsNameResolverBuilder, is available from the following locations:

    jar:file:/C:/Users/Administrator/.m2/repository/io/netty/netty-resolver-dns/4.1.35.Final/netty-resolver-dns-4.1.35.Final.jar!/io/netty/resolver/dns/DnsNameResolverBuilder.class

The called method's class hierarchy was loaded from the following locations:

    io.netty.resolver.dns.DnsNameResolverBuilder: file:/C:/Users/Administrator/.m2/repository/io/netty/netty-resolver-dns/4.1.35.Final/netty-resolver-dns-4.1.35.Final.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper and io.netty.resolver.dns.DnsNameResolverBuilder

17:15:03.818 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper.<clinit>(AddressResolverGroupProvider.java:58)

The following method did not exist:

    io.netty.resolver.dns.DnsNameResolverBuilder.socketChannelType(Ljava/lang/Class;)Lio/netty/resolver/dns/DnsNameResolverBuilder;

The calling method's class, io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper, was loaded from the following location:

    jar:file:/C:/Users/Administrator/.m2/repository/io/lettuce/lettuce-core/6.1.8.RELEASE/lettuce-core-6.1.8.RELEASE.jar!/io/lettuce/core/resource/AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper.class

The called method's class, io.netty.resolver.dns.DnsNameResolverBuilder, is available from the following locations:

    jar:file:/C:/Users/Administrator/.m2/repository/io/netty/netty-resolver-dns/4.1.35.Final/netty-resolver-dns-4.1.35.Final.jar!/io/netty/resolver/dns/DnsNameResolverBuilder.class

The called method's class hierarchy was loaded from the following locations:

    io.netty.resolver.dns.DnsNameResolverBuilder: file:/C:/Users/Administrator/.m2/repository/io/netty/netty-resolver-dns/4.1.35.Final/netty-resolver-dns-4.1.35.Final.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper and io.netty.resolver.dns.DnsNameResolverBuilder

